### ISSUE TITLE
Multiple instance problem

### ISSUE THREAD

**Issue by TradeFace** [TradeFace/mqttdevices#1]
Django runs __init__ two times. For the MQTT listener we want only one instance. I did a quick test with a singleton, which didn't quite work as expected (because of the double init call). Do you have an idea how this can be solved?   

Branch https://github.com/TradeFace/mqttdevices/tree/feature/mqttclient

**Comment by emontnemery** [comment]
Which init is run twice?

**Comment by TradeFace** [comment]
https://github.com/TradeFace/mqttdevices/blob/feature/mqttclient/web/web/__init__.py
https://github.com/TradeFace/mqttdevices/blob/feature/mqttclient/web/tuyamqtt/__init__.py

These two I have tested, both run twice.

**Comment by TradeFace** [comment]
I think this is the solution https://channels.readthedocs.io/en/latest/

**Comment by TradeFace** [comment]
https://stackoverflow.com/questions/2110545/why-is-init-module-in-django-project-loaded-twice
